return {
    -- Cubs
    "Brown Cub Skin",
    "Robo Cub Skin",
    "Stick Cub Skin",
    "Star Cub Skin",
    "Noob Cub Skin",
    "Bee Cub Skin",
    "Gingerbread Cub Skin",
    "Snow Cub Skin",
    "Peppermint Robo Cub Skin",
    "Doodle Cub Skin",
    "Gloomy Cub Skin",
    -- Hive skins
    "Wavy Purple Hive Skin",
    "Icy Crowned Hive Skin",
    "Wavy Doodle Hive Skin",
    "Wavy Cyan Hive Skin",
    -- Vouchers
    "Bear Bee Voucher",
    "Cub Buddy Voucher",
    "x2 Bee Gather Voucher",
    "x2 Convert Speed Voucher",
    "Offline Voucher",
    "Ticket Voucher",
    -- Stickers
    "Stranded Sun Bear",
    "Cyan Hilted Sword",
    "Black Star",
    "Nessie",
    "Ionic Column Top",
    "Ionic Column Middle",
    "Ionic Column Base",
    "Royal Symbol",
    "Party Robo Bear",
    "BBM From Below",
    "Black Diamond",
    "Round Basic Bee",
    "Glowering Gummy Bear",
    "Sitting Mother Bear",
    "Sideways Spirit Bear",
    "Left Shining Diamond Fleuron",
    "Right Shining Diamond Fleuron",
    "Left Mythic Gem Fleuron",
    "Right Mythic Gem Fleuron",
    "Prismatic Mushroom",
    "Dark Flame",
    "Glowing Smile",
    -- Star Signs
    "Capricorn Star Sign",
    "Aquarius Star Sign",
    "Pisces Star Sign",
    "Aries Star Sign",
    "Taurus Star Sign",
    "Gemini Star Sign",
    "Cancer Star Sign",
    "Leo Star Sign",
    "Virgo Star Sign",
    "Libra Star Sign",
    "Scorpio Star Sign",
    "Sagittarius Star Sign",
    -- Stamps
    "Pine Tree Forest Stamp",
    "Sunflower Field Stamp",
	"Dandelion Field Stamp",
	"Mushroom Field Stamp",
	"Blue Flower Field Stamp",
	"Clover Field Stamp",
	"Strawberry Field Stamp",
	"Spider Field Stamp",
	"Bamboo Field Stamp",
	"Pineapple Patch Stamp",
	"Stump Field Stamp",
	"Cactus Field Stamp",
	"Pumpkin Patch Stamp",
	"Pine Tree Forest Stamp",
	"Rose Field Stamp",
	"Hub Field Stamp",
	"Mountain Top Field Stamp",
	"Pepper Patch Stamp",
	"Coconut Field Stamp",
	"Ant Field Stamp",
    -- Tools
    "Scooper",
    "Rake",
    "Clippers",
    "Magnet",
    "Vacuum",
    "Super-Scooper",
    "Pulsar",
    "Electro-Magnet",
    "Scissors",
    "Honey Dipper",
    "Bubble Wand",
    "Scythe",
    "Golden Rake",
    "Spark Staff",
  -- Garbage as tests
--[[
    "Rubber Duck",
    "Simple Sun",
    "Simple Skyscraper",
	"Launching Rocket",
	"Pink Cupcake",
	"Red X"]]
}
